import { createRequire } from 'node:module';
import { createApp } from '../server.mjs';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.DOOH_PLAYWRIGHT_MODULE || 'playwright');
const temp = mkdtempSync(path.join(os.tmpdir(), 'dooh-browser-'));
const { server } = createApp({ dataDir: temp });
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const output = path.resolve('test-results'); mkdirSync(output, { recursive: true });
let browser;
const checks = [];
const check = message => { checks.push(message); console.log(`PASS ${message}`); };
try {
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '/?agents=browser');
  await page.waitForFunction(() => document.getElementById('online-count').textContent === '3');
  const player = id => page.frames().find(frame => frame.url().includes(`device=${id}`));
  await page.waitForTimeout(1500);
  assert.equal(page.frames().filter(frame => frame.url().includes('player.html')).length, 3);
  for (const id of ['screen-01', 'screen-02', 'screen-03']) assert.ok(await player(id).evaluate(() => doohDebug().assetId));
  check('three independent players start, cache files and send heartbeat');
  await page.screenshot({ path: path.join(output, '01-dashboard.png'), fullPage: true });
  const report = () => fetch(base + '/api/report').then(response => response.json());
  const post = (url, data) => fetch(base + url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }).then(response => response.json());
  await page.locator('#card-screen-03 [data-connection]').click();
  await player('screen-03').waitForFunction(() => !doohDebug().online);
  const before = (await report()).events.filter(e => e.device_id === 'screen-03').length;
  await player('screen-03').waitForFunction(() => doohDebug().queue >= 3, { timeout: 23000 });
  assert.equal((await report()).events.filter(e => e.device_id === 'screen-03').length, before);
  assert.ok(await player('screen-03').evaluate(() => doohDebug().assetId));
  check('simulated network loss preserves playback and queues PoP locally');
  await page.screenshot({ path: path.join(output, '02-offline.png'), fullPage: true });
  await page.locator('#card-screen-03 [data-connection]').click();
  await player('screen-03').waitForFunction(() => doohDebug().online && doohDebug().queue === 0);
  const events = (await report()).events;
  assert.ok(events.filter(e => e.device_id === 'screen-03').length > before);
  assert.equal(new Set(events.map(e => e.event_id)).size, events.length);
  check('reconnect delivers stored original-time events without duplicates');
  await page.locator('#card-screen-01 [data-pause]').click();
  await player('screen-01').waitForFunction(() => doohDebug().paused);
  const elapsed = await player('screen-01').evaluate(() => doohDebug().elapsed);
  await page.waitForTimeout(1000);
  assert.ok(Math.abs(await player('screen-01').evaluate(() => doohDebug().elapsed) - elapsed) < 250);
  await page.locator('#card-screen-01 [data-pause]').click();
  await player('screen-01').waitForFunction(() => !doohDebug().paused);
  check('pause freezes elapsed time; resume continues playback');
  await page.locator('#card-screen-02 [data-action=config]').click();
  await page.locator('#config-playlist').selectOption('cityloop');
  await page.locator('#config-form button[type=submit]').click();
  await player('screen-02').waitForFunction(() => doohDebug().playlistName === 'Городской цикл');
  check('dashboard publishes playlist configuration and player applies it');
  // Generate an actual short WebM from canvas: no external sample media or network.
  const upload = await page.evaluate(async () => {
    const canvas = document.createElement('canvas'); canvas.width = 1280; canvas.height = 720;
    const ctx = canvas.getContext('2d'); const stream = canvas.captureStream(20);
    const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp8' });
    const chunks = []; recorder.ondataavailable = event => chunks.push(event.data);
    const done = new Promise(resolve => { recorder.onstop = resolve; });
    const start = performance.now();
    const render = () => {
      ctx.fillStyle = '#24203a'; ctx.fillRect(0, 0, 1280, 720);
      ctx.fillStyle = '#a894ef'; ctx.beginPath(); ctx.arc(930 + Math.sin((performance.now() - start) / 500) * 80, 360, 150, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = '#ffffff'; ctx.font = 'bold 100px Arial'; ctx.fillText('DOOH / LIVE', 70, 350);
      ctx.font = '30px Arial'; ctx.fillText('Реальное видео · браузерный тест', 75, 420);
    };
    render(); const timer = setInterval(render, 50); recorder.start();
    await new Promise(resolve => setTimeout(resolve, 3000)); recorder.stop(); await done; clearInterval(timer); stream.getTracks().forEach(track => track.stop());
    const blob = new Blob(chunks, { type: 'video/webm' });
    const response = await fetch('/api/assets', { method: 'POST', headers: { 'Content-Type': 'video/webm', 'X-Filename': encodeURIComponent('DOOH live.webm') }, body: blob });
    if (!response.ok) throw new Error('Video upload failed'); return response.json();
  });
  const videoPlaylist = await post('/api/playlists', { name: 'Video test', items: [{ assetId: upload.id, duration: 8 }] });
  await post('/api/devices/screen-02/config', { playlistId: videoPlaylist.id });
  await player('screen-02').waitForFunction(() => document.querySelector('video')?.currentTime > .1);
  await page.waitForTimeout(5500);
  assert.ok((await report()).events.some(e => e.asset_id === upload.id && e.kind === 'completed'));
  check('real WebM upload, verified Blob cache, video playback and ended PoP');
  const startAt = new Date(Date.now() + 4500).toISOString(); const endAt = new Date(Date.now() + 10000).toISOString();
  await post('/api/devices/screen-01/config', { playlistId: 'creative', fallbackId: 'cityloop', startsAt: startAt, endsAt: endAt });
  await player('screen-01').waitForFunction(() => doohDebug().playlistName === 'Городской цикл');
  await player('screen-01').waitForFunction(() => doohDebug().playlistName === 'Новый сезон');
  await player('screen-01').waitForFunction(() => doohDebug().playlistName === 'Городской цикл');
  check('time-window scheduling switches from fallback to campaign and back');
  await page.getByRole('button', { name: 'Журнал показов', exact: false }).first().click();
  await page.locator('#event-kind').selectOption('completed');
  assert.ok(await page.locator('#event-rows tr').count() > 0);
  await page.screenshot({ path: path.join(output, '03-events.png'), fullPage: true });
  check('proof-of-play journal renders and filters server events');
  // Real server loss, plus reload of player shell through Service Worker.
  await page.getByRole('button', { name: 'Сеть экранов', exact: false }).first().click();
  await page.waitForFunction(() => !!navigator.serviceWorker.controller);
  await new Promise(resolve => server.close(resolve));
  await player('screen-03').waitForFunction(() => !doohDebug().online);
  assert.ok(await player('screen-03').evaluate(() => doohDebug().assetId));
  await player('screen-03').evaluate(() => location.reload());
  // The frame URL stays the same; wait for offline shell and restored IndexedDB.
  await page.waitForTimeout(5500);
  await player('screen-03').waitForFunction(() => !!window.doohDebug?.().assetId);
  check('actual server outage and offline player reload restore cached playback');
  await page.setViewportSize({ width: 390, height: 844 });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1);
  assert.equal(overflow, false);
  await page.screenshot({ path: path.join(output, '04-mobile.png'), fullPage: true });
  check('390px responsive dashboard has no horizontal overflow');
  assert.deepEqual(errors, []);
  check('no uncaught browser JavaScript errors');
  console.log(`${checks.length} browser checks passed. Screenshots: ${output}`);
} finally {
  await browser?.close();
  if (server.listening) await new Promise(resolve => server.close(resolve));
  // Only the exact task-owned mkdtemp directory is removed.
  assert.ok(temp.startsWith(path.join(os.tmpdir(), 'dooh-browser-')));
  rmSync(temp, { recursive: true, force: true });
}
